server:
  port: 9192

spring:
  datasource:
    username: dsvetiev
    password: ICUI4CU
    url: jdbc:mysql://localhost:3306/student_management_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: tru